bcos:
    cryptoMaterial:
        certPath: conf_dev

    network:
        peers:
            - 120.221.161.32:20200
            - 120.221.161.32:20201

    account:
        keyStoreDir: account
        accountFilePath: conf_dev/0x768d1a17d323b82afd47e7fbbe80c4e2b2b203f9.pem
        accountFileFormat: pem
        accountAddress: "0x768d1a17d323b82afd47e7fbbe80c4e2b2b203f9"

    threadPool:
        channelProcessorThreadSize: "16"
        receiptProcessorThreadSize: "16"
        maxBlockingQueueSize: "102400"

    contract:
        logger:
            address: "0x65048fa48d1d0650d31b50b3521559f78272f3a5"