cloud:
  chainmaker:
    chains:
      - chain-id: chain1
        org-id: wx-org1.chainmaker.org
        user-key-path: crypto-config-test/wx-org1.chainmaker.org/user/client1/client1.sign.key
        user-cert-path: crypto-config-test/wx-org1.chainmaker.org/user/client1/client1.sign.crt
    nodes:
      - grpc-url: grpcs://120.237.18.20:33088
        client-key-path: crypto-config-test/wx-org1.chainmaker.org/user/admin1/admin1.tls.key
        client-cert-path: crypto-config-test/wx-org1.chainmaker.org/user/admin1/admin1.tls.crt
        tls-cert-path: crypto-config-test/wx-org1.chainmaker.org/ca/ca.crt
        hostname: consensus1.tls.wx-org1.chainmaker.org
        ssl-provider: openSSL
        negotiation-type: TLS